### ISSUE TITLE
Generator always raising the interactive mode when parameters are passed

### ISSUE THREAD

**Issue by Panthro** [AdaptiveMe/generator-adaptiveme#50]
When the generator is called using parameteres like the following line:

`yo adaptiveme NOT_UNTITLED latest true "HTML5 Boilerplate" --skip-install --skip-server`

It starts the interactive mode instead of executing the generator with the given parameters:

```
$ yo adaptiveme NOT_UNTITLED latest true "HTML5 Boilerplate" --skip-install --skip-server
[generator-adaptive] Starting generator...
? What is the base name of your application? untitled1
```

It looks like the parameters are being ignored, check the difference between the **project title** parameter

**Comment by ferranvila** [comment]
Hi Rafael, I can't put the parameters required in the nibble start script. Because if I put them required, the interactive mode can not be used.

The "right" way to use the script (for developers) is the interactive way, but if they are using the IDE, this behaviour is bypassed / hidden from the user.

What do you thing?

PS: none of the parameters is required, but if you use one of them, you should put them all.

**Comment by Panthro** [comment]
I think if we state in the --help that all the parameters are necessary when using the "one command mode" it's OK

So they are not required to use the tool, but if you want to use as a "one liner" you need to pass all parameters.

And if the generator is started with only some parameters throw an error saying that the others are missing. 

Then the behaviour will be consistent, and the current scenario won't happen again.

Throwing an error in the user's face is always better than behaving in an unexpected way. :smiling_imp:

**Comment by ferranvila** [comment]
Solved.

Pass all the parameters > Not interactive mode
Pass any parameter > Interactive mode
Pass some parameters > Error
